### PR TITLE
updated gitignore for supporting various IDE

### PR DESCRIPTION
**Pull request by ohbus**
✔️  Users can now work on the following IDE without worrying about the generated machine files by them.
- [x] [Eclipse](https://www.eclipse.org/downloads/)
- [x] [VS Code](https://code.visualstudio.com/download)
- [x] [NetBeans](https://netbeans.apache.org/download/)

</br>

✔️ On top of the existing gitignore files for IDEA. Some file types have been added.

### CODE REVIEW

**Comment by sachishMaharjan** [comment]
Well Done.

**Review by JJS777 — APPROVED** [review]

**Review by JJS777 — APPROVED** [review]

**Review by JJS777 — APPROVED** [review]

**Comment by JJS777** [comment]
I'm not sure What has happened but I have some screen shoots, it shows back in September that this happened... I noticed my browser wasn't displaying a secure connection and was lead here with all the problems I'm having.. I just had a stock screening app open and it immediately brought me to Git Hub 1

**Review by JJS777 — APPROVED** [review]

**Review by JJS777 — APPROVED** [review]

**Review by JJS777 — APPROVED** [review]

**Comment by JJS777** [comment]
Thank you Gentle Men I appreciate the Help .. I had no 
Idea what had happened
thanks

**Comment by ehrenkret-signal** [comment]
closing out old conflicting PRs

**Pull request closed without merging**
