### PR TITLE
Uni tests only catered for -TIMEZONE, this is fixed

### PR DESCRIPTION
**Pull request by theyoz**

### CODE REVIEW

**Comment by theyoz** [comment]
I'd really like to participate, is there a list of issues (like a jira server somewhere?)

**Comment by jon-signal** [comment]
I think this looks good to merge, but could it looks like we have some conflicts to resolve first. Would you mind addressing those? Thanks!

**Comment by theyoz** [comment]
I will

**Comment by theyoz** [comment]
Hi,

I merged with current master. Project redos-dispatch wasn't building unless I also fixed the pom.xml. 

Regards

Yoram

**Comment by jon-signal** [comment]
Thank you for your effort, but it looks like there are still conflicts. Are you certain you've:

1. Pulled a recent copy of `master`?
2. Rebased your changes against `master`?

It's not clear to me why you've needed to make any changes to `pom.xml`, and I'm afraid we won't be able to accept those changes as part of this contribution. Let's see if we can get those merge conflicts sorted out first, then tackle the rest from there.

**Comment by theyoz** [comment]
Hi,

I'm at the current master:

git rev-parse HEAD
0572951c8a6fc2e137d688157b3df6cc61e97120

I'm not sure what merge conflict there is, also in github?

image

As for the pom, I'm build with maven and get failure without the change (see log attached). I removed it for this request. Can you let me know how to build without the pom changes?

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:analyze-only (analyze) on project redis-dispatch: Dependency problems found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:analyze-only (analyze) on project redis-dispatch: Dependency problems found`


[signal-build.zip](https://github.com/signalapp/Signal-Server/files/6291285/signal-build.zip)

**Comment by theyoz** [comment]
The build is failing but I'm not sure why? I've tried the pipeline command "mvn -e -B package" and it works for me, interestingly without the pom.xml changes so I guess it must be a problem only on **install** goal.

`Warning:  Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 6.294 s - in org.whispersystems.gcm.server.SimultaneousSenderTest
[INFO] Running org.whispersystems.gcm.server.SenderTest
Error:  Tests run: 7, Failures: 0, Errors: 6, Skipped: 1, Time elapsed: 0.039 s <<< FAILURE! - in org.whispersystems.gcm.server.SenderTest
Error:  org.whispersystems.gcm.server.SenderTest.testServerError  Time elapsed: 0.032 s  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)

Error:  org.whispersystems.gcm.server.SenderTest.testBadRequest  Time elapsed: 0.001 s  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)

Error:  org.whispersystems.gcm.server.SenderTest.testNotRegistered  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)

Error:  org.whispersystems.gcm.server.SenderTest.testServerErrorRecovery  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)

Error:  org.whispersystems.gcm.server.SenderTest.testBadApiKey  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)

Error:  org.whispersystems.gcm.server.SenderTest.testSuccess  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    SenderTest.testBadApiKey » Runtime java.net.BindException: Cannot assign reque...
Error:    SenderTest.testBadRequest » Runtime java.net.BindException: Cannot assign requ...
Error:    SenderTest.testNotRegistered » Runtime java.net.BindException: Cannot assign r...
Error:    SenderTest.testServerError » Runtime java.net.BindException: Cannot assign req...
Error:    SenderTest.testServerErrorRecovery » Runtime java.net.BindException: Cannot as...
Error:    SenderTest.testSuccess » Runtime java.net.BindException: Cannot assign request...`

**Comment by theyoz** [comment]
On last thing, there is another guy that tried to fixed the same problem

https://github.com/signalapp/Signal-Server/pull/118

He has merge conflict, maybe there lies the confusion.

**Comment by ehrenkret-signal** [comment]
Looks like the reason it is conflicting is that e3af0a13daaca382c3a813ab73fcd247b93b29dc resolved this problem with the unit tests.

**Pull request closed without merging**
