### PR TITLE
Unit test fixes

### PR DESCRIPTION
**Pull request by mdietz198**
I ran [pitest](http://pitest.org) and found two things:
1. An order dependency in the WebsocketControllerTest due to the static fields
2. Some assertThat lines that were not actually asserting anything

Using the pitest results, I added some more assertions and tests - mostly for error cases - in a [branch](https://github.com/mdietz198/TextSecure-Server/tree/add-pitest). If that help is appreciated, I can keep adding some more coverage and make another pull request. If not, no worries. If you're more interested in contributions to the client, I'd be happy to give that a shot.

### CODE REVIEW

**Comment by moxie0** [comment]
sorry I didn't see this before, looks like it needs a rebase

**Comment by mdietz198** [comment]
Looks like the first commit is no longer relevant since WebsocketControllerTest is gone. The other two commits still apply.

**Comment by moxie0** [comment]
sorry, it also looks like you haven't signed the CLA

**Comment by odeke-em** [comment]
Ping @mdietz198 -- after signing the CLA, perhaps a squash of the commits as well.

**Comment by posix4e** [comment]
Honestly I think this should be closed in favour of https://github.com/WhisperSystems/Signal-Server/pull/81

**Pull request closed without merging**
