### PR TITLE
Fix Readme and remove legacy base64 

### PR DESCRIPTION
**Pull request by posix4e**
This also officially moves maven to jdk8

// FREEBIE

### CODE REVIEW

**Comment by posix4e** [comment]
Do people want me to write any specific steps!

**Comment by posix4e** [comment]
This useful or should I close it out

**Comment by theilgaard** [comment]
@posix4e I found this very useful, thanks. Javadoc throughout the code would also be very welcomed, even though the code is slick and easy to read. 

The API documentation in the wiki is outdated.

**Comment by posix4e** [comment]
OK closing this out due to lack of interest. I still think this will cause obvious bugs.

**Pull request closed without merging**
