### PR TITLE
Require ASCII-only passwords.

### PR DESCRIPTION
**Pull request by jimpo**
Fixes https://github.com/WhisperSystems/TextSecure-Server/issues/21.

### CODE REVIEW

**Comment by odeke-em** [comment]
Ooh TextSecure-Server issues seem to have been lost, perhaps after repo migration. @moxie0 or other team folks, might y'all know what to do here?

**Comment by e-s-a-i** [comment]
ASCII-only passwords sounds like a horrible idea.

**Comment by posix4e** [comment]
There's not enough justification imho for this patch.

**Comment by jimpo** [comment]
Issue is lost and it seems this is not desired.

**Pull request closed without merging**
