### PR TITLE
Corrects docs

### PR DESCRIPTION
**Pull request by richardARPANET**

### CODE REVIEW

**Review by richtier — APPROVED** [review]
LGTM

**Review by JJS777 — APPROVED** [review]

**Comment by AceXare** [comment]
please just merge or explain

**Comment by lynn-stephenson** [comment]
As far as I can see from the AGPLv3 license, Signal is legally supposed to distribute the server source code to the users of it.

I don't see it as a good message to ignore the community, or leave us in the dark.

The issues tab is not available. Pull requests that should have been dealt with haven't been.

While Signal is the most secure messenger, I would hate to see it go down a “dark path” of proprietary nature. I don't think this is something to take lightly.

**Comment by lynn-stephenson** [comment]
@moxie0 Could you fill us in, please?

**Comment by joepie91** [comment]
> As far as I can see from the AGPLv3 license, Signal is legally supposed to distribute the server source code to the users of it.

This is true only if it contains substantial contributions to which Signal (the company) does not hold the copyright or special license. I don't know whether that is the case here, though the contributor list suggests "quite possibly not".

That having been said, that's just the legal side of it. There are many non-legality-related reasons why the server code should be published, auditability being one of them.

**Comment by richardARPANET** [comment]
@ehrenkret-signal, blink twice if you need help

**Pull request closed without merging**
