### PR TITLE
Move duplicated Mexico number formatting to single method

### PR DESCRIPTION
**Pull request by dmuml10**

### CODE REVIEW

**Review by jon-signal — APPROVED** [review]

**Comment by neerajsu** [comment]
So.... Why does this code not have issues tab? Everything else has issues tab. 

Also, where are your servers hosted? If you actually have access to the server, you can intercept traffic even if your clients have all this ENCRYPTION.

Please document complete architecture on GitHub with exact information. That is called open source. 

@GitHub : Please enable issues tab on this "open" source repository.

**Comment by lus** [comment]
@neerajsu The protocol used by Signal is entirely open sourced (see [here](https://signal.org/docs/) and [here](https://github.com/signalapp/libsignal)).
Additionally, not allowing issues on an open source repository can actually have very good reasons. There are enough ways to contact the Signal staff regarding bug reports or general questions. Creating a single central support channel for all support requests is completely understandable, especially when considering that not everybody who uses Signal has a GitHub account.

**Comment by jon-signal** [comment]
@dmuml10 Thank you for the contribution! We've actually moved all of this logic into our new [stand-alone registration service](https://github.com/signalapp/registration-service), and so I'm afraid this pull request is now pointed at code that has since been removed from this repository. Please accept my apologies for not merging this sooner.

That said, this _does_ make me realize that we need to add similar code to the new registration service, and I'll do that first thing tomorrow morning.

Cheers, and thanks again!

**Comment by jon-signal** [comment]
On further reading, it sounds like the dialing plan for Mexico has changed, and this is no longer necessary at all.

**Pull request closed without merging**
